services:
  db:
    image: postgres:18
    container_name: justmail-postgres
    environment:
      POSTGRES_USER: ${APP_DATABASE__USERNAME}
      POSTGRES_PASSWORD: ${APP_DATABASE__PASSWORD}
      POSTGRES_DB: ${APP_DATABASE__DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql
    networks:
      - justmail
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-backup:
    image: prodrigestivill/postgres-backup-local:16
    container_name: justmail-db-backup
    restart: always
    user: root
    volumes:
      - ${DB_BACKUP_LOCATION}:/backups
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ${APP_DATABASE__DATABASE_NAME}
      POSTGRES_USER: ${APP_DATABASE__USERNAME}
      POSTGRES_PASSWORD: ${APP_DATABASE__PASSWORD}
      SCHEDULE: "0 2 * * *"
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - justmail

  redis:
    image: redis:8
    container_name: justmail-redis
    networks:
      - justmail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    container_name: justmail-migrator
    build:
      context: .
    environment:
      DATABASE_URL: postgres://${APP_DATABASE__USERNAME}:${APP_DATABASE__PASSWORD}@${APP_DATABASE__HOST}:${APP_DATABASE__PORT}/${APP_DATABASE__DATABASE_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - justmail
    entrypoint: ["sqlx", "migrate", "run"]

  justmail:
    container_name: justmail
    build:
      context: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - justmail
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.justmail.rule=Host(`justmail.bymaris.one`)"
      - "traefik.http.routers.justmail.entrypoints=websecure"
      - "traefik.http.services.justmail.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://justmail:8000/health_check"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  web:
    external: true
    name: backbone_web
  justmail:
    driver: bridge
