#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
    CREATE USER "${APP_DATABASE__USERNAME}" WITH PASSWORD '${APP_DATABASE__PASSWORD}';
    ALTER USER "${APP_DATABASE__USERNAME}" CREATEDB;
EOSQL
